#!/bin/bash

function link() {
    source=$1
    dest=/home/git/data/$2
    
    if [[ -d $source && ! -d $dest ]]; then
        mv $source $dest && ln -s $dest $source
    elif [[ -d $dest ]]; then
        if [[ ! -h $source ]]; then
            rsync -avpz --ignore-existing $source/ $dest/
            rm -fr $source && ln -s $dest $source
        elif [[ ! -e $source ]]; then
            ln -s $dest $source
        fi
    elif [[ -f $source && ! -h $source ]]; then
        cp $source $dest && ln -sf $dest $source  
    fi 
}

# Make sure some things are moved/pointed to our persistent data directory
# logs
link /home/git/gitlab/log log 
link /home/git/gitlab/config config
link /home/git/gitlab-shell/config.yml config/config.yml
link /etc/nginx/conf.d/gitlab.conf config/nginx.conf
link /home/git/gitlab.crt config/gitlab.crt
link /home/git/gitlab.key config/gitlab.key

chown git:git /home/git/data
chown git:git /home/git/data/authorized_keys
chmod 644 /home/git/data/authorized_keys
chmod 600 /home/git/config/gitlab.key
chown www-data /home/git/config/gitlab.key

# Have to daemonize postfix.  Sucks.
/etc/init.d/postfix start

# sshd priv sep directory
[[ ! -d /var/run/sshd ]] && mkdir /var/run/sshd

/usr/bin/supervisord -n
