#!/bin/bash

# Point sidekiq at our redis server
echo "production: redis://${REDIS_HOST}" > /home/git/gitlab/config/resque.yml

# Update nginx config
sed -ie "s/YOUR_URL_HERE/${GITLAB_HOST}/" /etc/nginx/conf.d/gitlab.conf

# Update gitlab.yml
sed -ie "s/YOUR_URL_HERE/${GITLAB_HOST}/" /home/git/gitlab/config/gitlab.yml
chown git /home/git/gitlab/config/gitlab.yml

# Update config.yml
REDIS_HOST=$(echo $REDIS_HOST | awk -F: '{ print $1 }')
sed -ie "s/REDIS_HOST/${REDIS_HOST}/" /home/git/gitlab-shell/config.yml
chown git /home/git/gitlab-shell/config.yml

# Validate permissions on repos directory (doesn't work)
chmod -R ug+rwX,o-rwx /home/git/repositories/
chmod -R ug-s /home/git/repositories/
find /home/git/repositories/ -type d -print0 | sudo xargs -0 chmod g+s

# Have to daemonize postfix.  Sucks.
/etc/init.d/postfix start

/usr/bin/supervisord -n
